const FETCH_TODOS = 'FETCH_TODOS';
const CREATE_TODO = 'CREATE_TODO';
const UPDATE_TODO = 'UPDATE_TODO';
const DELETE_TODO = 'DELETE_TODO';
const SHOW_MODAL = 'SHOW_MODAL';
const HIDE_MODAL = 'HIDE_MODAL';

export {
  FETCH_TODOS,
  CREATE_TODO,
  UPDATE_TODO,
  DELETE_TODO,
  SHOW_MODAL,
  HIDE_MODAL,
};
